# SRC = $(wildcard *.c)
# OBJS = $(SRC:.c=.o)
# NAME = nmellal
# CC = cc
# INC = ../../includes
# CFLAGS = -Wall -Werror -Wextra -I$(INC) -g3 -fsanitize=address
# LDFLAGS = -lreadline

# all : $(NAME)

# $(OBJS) : %.o : %.c
# 	$(CC) $(CFLAGS) -c $< -o $@

# $(NAME) : $(OBJS)
# 	$(CC) $(CFLAGS) $(OBJS) -o $(NAME) $(LDFLAGS)


# clean :
# 	rm -f $(OBJS)

# fclean : clean

# re : fclean all

# .PHONY : re fclean clean all

# .SECONDARY : $(OBJS)
